CREATE SEQUENCE SEQUENCE_GROUPS NOCACHE;
-- CREATE TABLE
CREATE TABLE GROUPS
(
  ID            NUMBER NOT NULL,
  USER_ID       NUMBER NOT NULL,
  DESCRIPTION   VARCHAR2(255) NOT NULL,
  CREATION_DATE DATE DEFAULT SYSDATE,
  UPDATE_DATE   DATE DEFAULT SYSDATE
);
-- CREATE/RECREATE INDEXES 
CREATE INDEX FK_GROUPS_USERS ON GROUPS (USER_ID);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE GROUPS
  ADD CONSTRAINT PK_GROUPS PRIMARY KEY (ID)
  USING INDEX;
ALTER TABLE GROUPS
  ADD CONSTRAINT FK_GROUPS_USERS FOREIGN KEY (USER_ID)
  REFERENCES USERS (ID);