CREATE SEQUENCE SEQUENCE_MEDIAS NOCACHE;
-- CREATE TABLE
CREATE TABLE MEDIAS
(
  ID            NUMBER NOT NULL,
  USER_ID       NUMBER NOT NULL,
  TYPE          VARCHAR2(15) NOT NULL,
  TITLE         VARCHAR2(255) NOT NULL,
  CITY          NUMBER,
  DIRECTORY     VARCHAR2(255) NOT NULL,
  DURATION      NUMBER DEFAULT 60 NOT NULL,
  CREATION_DATE DATE DEFAULT SYSDATE,
  UPDATE_DATE   DATE DEFAULT SYSDATE
);
-- CREATE/RECREATE INDEXES 
CREATE INDEX FK_MEDIAS_USERS ON MEDIAS (USER_ID);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE MEDIAS
  ADD CONSTRAINT PK_MEDIAS PRIMARY KEY (ID)
  USING INDEX;
ALTER TABLE MEDIAS
  ADD CONSTRAINT FK_MEDIAS_USERS FOREIGN KEY (USER_ID)
  REFERENCES USERS (ID);