CREATE SEQUENCE SEQUENCE_PUBLICATIONS NOCACHE;
-- CREATE TABLE
CREATE TABLE PUBLICATIONS
(
  ID            NUMBER NOT NULL,
  ORDINATION    NUMBER NOT NULL,
  GROUP_ID      NUMBER,
  USER_ID       NUMBER,
  MEDIA_ID      NUMBER NOT NULL,
  CREATION_DATE DATE DEFAULT SYSDATE,
  UPDATE_DATE   DATE DEFAULT SYSDATE
);
-- CREATE/RECREATE INDEXES 
CREATE INDEX FK_PUBLICATIONS_GROUPS ON PUBLICATIONS (GROUP_ID);
CREATE INDEX FK_PUBLICATIONS_MEDIAS ON PUBLICATIONS (MEDIA_ID);
CREATE INDEX FK_PUBLICATIONS_USERS ON PUBLICATIONS (USER_ID);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE PUBLICATIONS
  ADD CONSTRAINT PK_PUBLICATIONS PRIMARY KEY (ID)
  USING INDEX;
ALTER TABLE PUBLICATIONS
  ADD CONSTRAINT FK_PUBLICATIONS_GROUPS FOREIGN KEY (GROUP_ID)
  REFERENCES GROUPS (ID);
ALTER TABLE PUBLICATIONS
  ADD CONSTRAINT FK_PUBLICATIONS_MEDIAS FOREIGN KEY (MEDIA_ID)
  REFERENCES MEDIAS (ID);
ALTER TABLE PUBLICATIONS
  ADD CONSTRAINT FK_PUBLICATIONS_USERS FOREIGN KEY (USER_ID)
  REFERENCES USERS (ID);