CREATE OR REPLACE VIEW SHOW_PUBLICATION_USER AS
SELECT A.ID,
       A.ORDINATION,
       A.MEDIA_ID,
       A.USER_ID,
       A.GROUP_ID,
       B.TYPE_MEDIA,
       B.TITLE,
       B.CITY,
       B.DIRECTORY,
       B.DURATION,
       A.USER_ID USERS
  FROM PUBLICATIONS A, MEDIAS B
 WHERE A.MEDIA_ID = B.ID
   AND A.USER_ID IS NOT NULL
UNION
SELECT A.ID,
       A.ORDINATION,
       A.MEDIA_ID,
       A.USER_ID,
       A.GROUP_ID,
       B.TYPE_MEDIA,
       B.TITLE,
       B.CITY,
       B.DIRECTORY,
       B.DURATION,
       C.USER_ID USERS
  FROM PUBLICATIONS A, MEDIAS B, PLEACES C
 WHERE A.MEDIA_ID = B.ID
   AND A.GROUP_ID = C.GROUP_ID
 ORDER BY ORDINATION;